server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kaijiegeng/springcloud-config.git
          search-paths:
            - springcloud-config
          username: 137423445@qq.com
          password: gkaijie090102.
      label: main

